theme = "tokyonight"

[editor]
line-number = "absolute"
mouse = true
middle-click-paste = false
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
