local M = {}

M.treesitter = {
  ensure_installed = {
    "c",
    "cmake",
    "comment",
    "cpp",
    "css",
    "diff",
    "dockerfile",
    "dot",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "go",
    "gomod",
    "gosum",
    "gowork",
    "graphql",
    "hcl",
    "html",
    "http",
    "java",
    "javascript",
    "jq",
    "json",
    "json5",
    "jsonc",
    "kotlin",
    "lua",
    "make",
    "markdown",
    "markdown_inline",
    "nix",
    "python",
    "regex",
    "rust",
    "scss",
    "sql",
    "todotxt",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vue",
    "yaml",
    "zig",
  },
  indent = {
    enable = true,
    disable = {
      "python"
    },
  },
}

M.mason = {
  ensure_installed = {
    "bash-language-server",
    "black",
    "clangd",
    "cmake-language-server",
    "cmakelang",
    "commitlint",
    "cpplint",
    "css-lsp",
    "deno",
    "fourmolu",
    "gitlint",
    "go-debug-adapter",
    "goimports-reviser",
    "golangci-lint-langserver",
    "gopls",
    "gradle-language-server",
    "grammarly-languageserver",
    "html-lsp",
    "jdtls",
    "jedi-language-server",
    "jq",
    "json-lsp",
    "json-to-struct",
    "jsonlint",
    "kotlin-debug-adapter",
    "kotlin-language-server",
    "ktlint",
    "lemminx",
    "lua-language-server",
    "markdownlint",
    "nginx-language-server",
    "prettier",
    "prettier",
    "sql-formatter",
    "sqls",
    "stylua",
    "terraform-ls",
    "tflint",
    "twigcs",
    "typescript-language-server",
    "vim-language-server",
    "yamllint",
    "zk",
    "zls",
  },
}

-- git support in nvimtree
M.nvimtree = {
  git = {
    enable = true,
  },
  renderer = {
    highlight_git = true,
    icons = {
      show = {
        git = true,
      },
    },
  },
}

return M
